/* Service worker — offline support for Čtecí ZOO.
 *
 * Strategy:
 *   - install: precache the app shell + content JSONs, then every animal
 *     image listed in the manifest (≈3.5 MB) and — when generated — every
 *     voice clip listed in assets/voice/manifest.json (≈10 MB, one-time).
 *   - fetch: images and audio are cache-first (they never change for a
 *     given hash); everything else is network-first with cache fallback,
 *     so code and content updates arrive on the next online launch while
 *     the app still works fully offline.
 *
 * Bump VERSION on releases that should force a clean re-cache.
 */
const VERSION = 'reading-zoo-v5';

const CORE = [
  './',
  './index.html',
  './styles.css',
  './manifest.webmanifest',
  './js/data.js',
  './js/lifecycle.js',
  './js/state.js',
  './js/speech.js',
  './js/lessons.js',
  './js/tasks.js',
  './js/views.js',
  './js/app.js',
  './data/content/curriculum_v2.json',
  './data/content/animals_50_seed.json',
  './data/content/stories.json',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png'
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    await cache.addAll(CORE);
    // Animal images come from the manifest so the list never drifts.
    try {
      const res = await cache.match('./data/content/animals_50_seed.json');
      const doc = await res.json();
      const images = (doc.animals || []).map((a) => './' + a.imagePath);
      await cache.addAll(images);
    } catch (err) {
      // Offline images are best-effort; the app still works without them.
      console.warn('[SW] animal image precache failed', err);
    }
    // Voice clips are optional (generated by scripts/generate-voice.mjs);
    // a missing manifest just means the app keeps using Web Speech.
    try {
      const res = await fetch('./assets/voice/manifest.json');
      if (res.ok) {
        await cache.put('./assets/voice/manifest.json', res.clone());
        const doc = await res.json();
        const clips = Object.values(doc.files || {}).map((f) => './assets/voice/' + f);
        await cache.addAll(clips);
      }
    } catch (err) {
      console.warn('[SW] voice precache skipped', err);
    }
    // Activate on a fresh session; never replace an active lesson.
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n.startsWith('reading-zoo-v') && n !== VERSION).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(new URL('./', self.location.href).pathname)) return;

  // Images and voice clips never change for a given filename → cache-first.
  const isStaticAsset = /\.(png|svg|jpg|webp|ico|mp3|wav|ogg)$/.test(url.pathname);

  event.respondWith((async () => {
    const cache = await caches.open(VERSION);

    // Code and curriculum form one release snapshot. Bump VERSION to update.
    const coreHit = await cache.match(req);
    const isCore = CORE.some((path) => new URL(path, self.location.href).pathname === url.pathname);
    if (coreHit && isCore) return coreHit;
    if (req.mode === 'navigate') {
      const shell = await cache.match('./index.html');
      if (shell) return shell;
    }

    if (isStaticAsset) {
      // cache-first
      const hit = await cache.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok) await cache.put(req, res.clone());
      return res;
    }

    // network-first with cache fallback (keeps code/content fresh online)
    try {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 8000);
      let res;
      try { res = await fetch(req, { signal: controller.signal }); }
      finally { clearTimeout(timeout); }
      if (!res.ok) throw new Error('HTTP ' + res.status);
      if (res.ok) await cache.put(req, res.clone());
      return res;
    } catch (err) {
      const hit = await cache.match(req)
        || (req.mode === 'navigate' ? await cache.match('./index.html') : null);
      if (hit) return hit;
      throw err;
    }
  })());
});
